sudo: false
language: c++
addons:
  apt:
    packages:
    - scons
    - gcc-4.7
    - libeigen3-dev
    - libprotobuf-dev
    - protobuf-compiler
install:
  - uname -a
  - g++ --version
  - ls /usr/bin/g++*
script:
  - scons
